### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by Honey-Whiskers** [DavidJCobb/eso-ItemTrig#14]
Sorry if this isn't the right place to put this!
I'm new to GitHub.

And also, thank you for the add-on, it looks super awesome.
I've been trying to find a good add-on to manage the Countess's items, and I noticed this one does it!

Getting the following errors on logging in:
`user:/AddOns/ItemTrig/misc/savedata.lua:155: attempt to index a nil value
stack traceback:
user:/AddOns/ItemTrig/misc/savedata.lua:155: in function 'ISavedataForAccount:character'
user:/AddOns/ItemTrig/savedata.lua:47: in function 'ItemTrig.Savedata:load'
user:/AddOns/ItemTrig/ItemTrig.lua:468: in function 'Initialize'
user:/AddOns/ItemTrig/ItemTrig.lua:547: in function 'OnAddonLoaded'
`

No other add-ons are enabled, variables have been cleared, and the add-on has been freshly reinstalled.
Could be related to the font being white on white?
![eso64_2019-05-03_15-39-58](https://user-images.githubusercontent.com/49449281/57161518-d1569300-6db9-11e9-9ac9-66571d72c587.png)

**Comment by DavidJCobb** [comment]
The font being white on white is a symptom, not a cause: ItemTrig lets you pick a color scheme, and in this case it doesn't know which one to use. Something may be wrong with your savedata. I need you to send me your SavedVariables file for ItemTrig.

~~The other possibility is that an update broke ItemTrig's ability to create new savedata from scratch. I try to actually use the mods I develop so that I'll be as likely to notice issues as anyone else, but for ESO, that means I can't easily test from a blank slate. I'll look into that possibility.~~ Just tested; it isn't this.

**Comment by Honey-Whiskers** [comment]
After you mentionned the variables, I looked into the file.
I'm not sure why, but it was for a secondary account of mine, with no mentions of my main account (the one I'm logged into in that screenshot).
I do sometimes run two sessions at once, so maybe that has something to do with it.

Upon deleting the saved variables and starting over, it seems to be fine now.

Thanks a bunch!
